<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Are you sure you want to delete this item?' => '',
	'Authorize'                                  => '',
	'Auto Replies'                               => '',
	'Can`\'t find conversation'                  => '',
	'Cancel'                                     => '',
	'Comment ID'                                 => '',
	'Comments'                                   => '',
	'Content'                                    => '',
	'Conversation Detail ID'                     => '',
	'Conversation ID'                            => '',
	'Conversation locked by {username}'          => '',
	'Conversations'                              => '',
	'Create Auto Reply'                          => '',
	'Created At'                                 => '',
	'Created Time'                               => '',
	'Data'                                       => '',
	'Delete'                                     => '',
	'Facebook Comment ID'                        => '',
	'Facebook Configuration'                     => '',
	'Facebook Reply Comment ID'                  => '',
	'Failed to fetch data.'                      => '',
	'Failed to locked.'                          => '',
	'Failed to revoke.'                          => '',
	'Failed to set customer.'                    => '',
	'Failed to transfer.'                        => '',
	'Failed to unlocked.'                        => '',
	'First'                                      => '',
	'Get Access Token'                           => '',
	'Hook Link'                                  => '',
	'ID'                                         => '',
	'Id'                                         => '',
	'Id Social Hook Request'                     => '',
	'Key'                                        => '',
	'Keyword...'                                 => '',
	'LHC Configuration'                          => '',
	'Last'                                       => '',
	'Lock'                                       => '',
	'Locked Successfully.'                       => '',
	'Login callback URL'                         => '',
	'Logout callback URL'                        => '',
	'Message'                                    => '',
	'Message Count'                              => '',
	'Module Config'                              => '',
	'Msg ID'                                     => '',
	'Name'                                       => '',
	'Receiver ID'                                => '',
	'Receiver Name'                              => '',
	'Reply Comment ID'                           => '',
	'Reply Content'                              => '',
	'Reset'                                      => '',
	'Revoke'                                     => '',
	'Revoked Successfully.'                      => '',
	'Save'                                       => '',
	'Search'                                     => '',
	'Select'                                     => '',
	'Select page'                                => '',
	'Send message error'                         => '',
	'Send ticket'                                => '',
	'Sender ID'                                  => '',
	'Sender Name'                                => '',
	'Set customer'                               => '',
	'Status'                                     => '',
	'Successfully fetched data.'                 => '',
	'Successfully set customer.'                 => '',
	'The requested page does not exist.'         => '',
	'Title'                                      => '',
	'Transfer'                                   => '',
	'Transfer Successfully.'                     => '',
	'Type'                                       => '',
	'Unauthorized'                               => '',
	'Unlock'                                     => '',
	'Unlocked Successfully.'                     => '',
	'Unread Count'                               => '',
	'Update'                                     => '',
	'Update Auto Reply: {nameAttribute}'         => '',
	'Update Social Configuration'                => '',
	'Update config success'                      => '',
	'Updated At'                                 => '',
	'Value'                                      => '',
	'Webhook'                                    => '',
	'Zalo Configuration'                         => '',
	'load old message'                           => '',
	'loading ...'                                => '',
];
